services:
  orderbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderbot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite+aiosqlite:///./data/orderbot.db
      - LOG_LEVEL=DEBUG
    volumes:
      - ./data:/app/data
      - ./images:/app/images
      - ./logs:/app/logs
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"
    # 安全配置
    security_opt:
      - no-new-privileges:true
    # 资源监控
    labels:
      - "monitoring.enabled=true"
      - "monitoring.service=orderbot"